version: "3"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raptgen
      PGDATA: /var/lib/postgresql/data/pgdata

  visualizer:
    build:
      context: ./visualizer
      dockerfile: Dockerfile
    container_name: frontend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./visualizer:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "yarn install; yarn next build; yarn next start"

  back:
    build:
      context: ./raptgen
      dockerfile: cpu.Dockerfile
    container_name: backend
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./raptgen:/app
    environment:
      - PYTHONPATH=/app
    command: sh -c "uvicorn --host 0.0.0.0 api:app"

  redis:
    image: redis
    container_name: redis
    ports:
      - 8030:6379

  worker:
    build:
      context: ./raptgen
      dockerfile: cpu.Dockerfile
    container_name: worker
    tty: true
    depends_on:
      - redis
    volumes:
      - ./raptgen:/app
    environment:
      - PYTHONPATH=/app
    user: "${UID}:${GID}"
    command: sh -c "celery --app=tasks.celery worker --loglevel=info --pool=threads"

  flower:
    build:
      context: ./raptgen
      dockerfile: cpu.Dockerfile
    container_name: flower
    tty: true
    depends_on:
      - redis
    volumes:
      - ./raptgen:/app
    environment:
      - PYTHONPATH=/app
    command: sh -c "celery --app=tasks.celery flower --port=5555"
    ports:
      - 8010:5555
